FROM node:lts-alpine

WORKDIR /usr/src/app

ENV NPM_CONFIG_LOGLEVEL warn

COPY package.json . 

RUN npm install --production --no-optional --silent && npm cache clean --force

COPY . .

CMD ["npm", "start"]